<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="0" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2020-02-23T17:51:13Z" name="Default suite" finished-at="2020-02-23T17:52:16Z" duration-ms="63321">
    <groups>
    </groups>
    <test started-at="2020-02-23T17:51:13Z" name="Default test" finished-at="2020-02-23T17:52:16Z" duration-ms="63321">
      <class name="Run.TestData">
        <test-method is-config="true" signature="beforeClass()[pri:0, instance:Run.TestData@609cd4d8]" started-at="2020-02-23T17:51:13Z" name="beforeClass" finished-at="2020-02-23T17:51:19Z" duration-ms="6368" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method signature="f(java.lang.Integer, java.lang.String)[pri:0, instance:Run.TestData@609cd4d8]" started-at="2020-02-23T17:51:19Z" name="f" data-provider="dp" finished-at="2020-02-23T17:51:19Z" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.Error: Unresolved compilation problems: 
Syntax error on token "@", , expected
gmail cannot be resolved to a variable
demo345 cannot be resolved to a variable
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.Error: Unresolved compilation problems: 
Syntax error on token "@", , expected
gmail cannot be resolved to a variable
demo345 cannot be resolved to a variable

at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:49)
at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:131)
at org.testng.internal.Parameters.handleParameters(Parameters.java:706)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:49)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:37)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:924)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.Error: Unresolved compilation problems: 
Syntax error on token "@", , expected
gmail cannot be resolved to a variable
demo345 cannot be resolved to a variable

at Run.TestData.dp(TestData.java:32)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:74)
at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:45)
... 22 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
        <test-method signature="Login()[pri:1, instance:Run.TestData@609cd4d8]" started-at="2020-02-23T17:51:19Z" name="Login" finished-at="2020-02-23T17:51:46Z" duration-ms="26892" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login -->
        <test-method signature="ForgotAccount()[pri:2, instance:Run.TestData@609cd4d8]" started-at="2020-02-23T17:51:46Z" name="ForgotAccount" finished-at="2020-02-23T17:52:12Z" duration-ms="25858" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ForgotAccount -->
        <test-method is-config="true" signature="afterClass()[pri:0, instance:Run.TestData@609cd4d8]" started-at="2020-02-23T17:52:12Z" name="afterClass" finished-at="2020-02-23T17:52:16Z" duration-ms="4155" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- Run.TestData -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
